### PR TITLE
[JENKINS-64236] Table to div compatibility + Update the minimum Jenkins core requirement to 2.204.6 + Update Parent POM to a recent version 

### PR DESCRIPTION
**Pull request by res0nance**

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Looks good to me. I am not sure why we enable incrementals in all plugins by default, but whatever

**Comment by timja** [comment]
> Looks good to me. I am not sure why we enable incrementals in all plugins by default, but whatever

it makes adding it to a docker image easier if you have to use it while waiting for the maintainer to merge / release

**Comment by res0nance** [comment]
@blakmajk could you PTAL at this as it is blocking users

**Comment by theta682** [comment]
This PR breaks connectivity. When I push "Test Connection" button it returns `ERROR` on Jenkins 2.235.5.

**Pull request merged**
